name: build and test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependency (ubuntu)
        run: |
          sudo apt -qy install \
              build-essential make libgtest-dev pybind11-dev \
              python3 python3-pip python3-pybind11 python3-pytest
      - name: build
        run: make
      - name: gtest
        run: make gtest
